config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'product_variants/new'
    get 'product_variants/edit'
  end
  devise_for :users
  root to: 'pages#home'
  namespace :admin do
    resources :categories
    resources :products do
      resources :product_variants, only: [:new, :create, :edit, :update]
    end
    resources :product_variants, only: [:index, :show, :destroy]
  end
  resources :product_variants, only: [:index, :show] do
    resources :basket_items, only: [:create]
  end
  get '/basket', to: 'baskets#show'
  resources :orders, only: [:create, :show]
  resources :basket_items, only: [:index, :destroy]
  resources :addresses, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items

  def empty?
    basket_items.empty?
  end

  def empty!
    basket_items.destroy_all
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket = find_or_create_basket
  end
end

app/views/baskets/show.html.erb
<h1>My Basket</h1>
<div class="d-flex w-100">
  <p>Item-</p>
  <p>Price-</p>
  <p>Quantity-</p>
  <p>Total</p>
</div>
<% @basket.basket_items.each do |bi| %>
  <div class="d-flex w-100">
  <p><%= bi.product_variant.name %>-</p>
  <p>£<%= bi.product_variant.price %>-</p>
  <p><%= bi.quantity %>-</p>
  <p>£<%= bi.product_variant.price.to_i * bi.quantity.to_i %></p>
  <%= link_to basket_item_path(bi), method: :delete do %>
    <i class="fas fa-times"></i>
  <% end %>
    </div>
<% end %>

<% if @basket.basket_items != [] %>
  <%= link_to "Checkout", orders_new_path %>
<% else %>
  <%= link_to "Empty, add some items", product_variants_path %>
<% end %>