config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'product_variants/new'
    get 'product_variants/edit'
  end
  devise_for :users
  root to: 'pages#home'
  namespace :admin do
    resources :categories
    resources :products do
      resources :product_variants, only: [:new, :create, :edit, :update]
    end
    resources :product_variants, only: [:index, :show, :destroy]
  end
  resources :product_variants, only: [:index, :show] do
    resources :basket_items, only: [:create]
  end
  get '/basket', to: 'baskets#show'
  resources :orders, only: [:create, :show]
  resources :basket_items, only: [:index, :destroy]
  resources :addresses, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :order, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items

  def empty?
    basket_items.empty?
  end

  def empty!
    basket_items.destroy_all
  end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :basket
  belongs_to :product_variant
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_items, dependent: :destroy
  has_many :product_variants, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product_variant
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_variants, dependent: :destroy
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
  has_many :basket_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :basket, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders
  has_many :product_variants, through: :order_items
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def create
    @address = Address.new(address_params)
    @address.user = current_user
    if @address.save
      redirect_back fallback_location: products_path
    else
      render 'orders/new'
    end
  end

  private

  def address_params
    params.require(:address).permit(:name, :line1, :line2, :postcode, :city, :county)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

# Need to add a combine baskets condition if a user logs in after adding items
# to their session based basket which transfers the items over to their devise basket

  def find_or_create_basket
    if current_user
      if current_user.basket && session[:basket_id]
        combine_baskets
      end
      if current_user.basket
        current_user.basket
      else
        Basket.create(user: current_user)
      end
    else
      if session[:basket_id] && Basket.find(session[:basket_id])
        Basket.find(session[:basket_id])
      else
        basket = Basket.create
        session[:basket_id] = basket.id
        basket
      end
    end
  end

  def combine_baskets
    old_basket = Basket.find(session[:basket_id])
    session[:basket_id] = nil
    new_basket = current_user.basket
    old_basket.basket_items.each do |item|
      item.update(basket: new_basket)
    end
    old_basket.destroy
    new_basket
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  def create
    @basket = find_or_create_basket
    @product_variant = ProductVariant.find(params[:product_variant_id])
    @basket_item = BasketItem.new(basket_item_params)
    @basket_item.basket = @basket
    @basket_item.product_variant = @product_variant
    if @basket_item.save
      redirect_to product_variants_path
    else
      raise
    end
  end

  def destroy
    @basket_item = BasketItem.find(params[:id])
    @basket_item.destroy
    redirect_to basket_path
  end

  private

  def basket_item_params
    params.require(:basket_item).permit(:quantity)
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket = find_or_create_basket
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category =Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @basket = find_or_create_basket
    @user = @basket.user
    @order = Order.new
    @address = Address.new
  end

  def create
    @basket = find_or_create_basket
    @order = Order.new(order_params)
    @order.user = current_user
    @order.address = current_user.addresses.first
    if @order.save
      @basket.basket_items.each do |item|
        order_item = OrderItem.new(
                      product_variant: item.product_variant,
                      quantity: item.quantity,
                      order: @order
                    )
        order_item.order = @order
        order_item.save
      end
      @basket.empty!
      redirect_to order_path(@order)
    else
      raise
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  def index
    @product_variants = ProductVariant.all
  end

  def show
    @product_variant = ProductVariant.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to categories_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to product_variants_path, class: "navbar-brand" do %>
    <h3>Home</h3>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Basket", basket_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Variants", product_variants_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/fanninggg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Admin Products Variants", admin_product_variants_path, class: "dropdown-item" %>
            <%= link_to "Admin Products", admin_products_path, class: "dropdown-item" %>
            <%= link_to "Admin Categories", admin_categories_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>