config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'product_variants/new'
    get 'product_variants/edit'
  end
  devise_for :users
  root to: 'pages#home'
  namespace :admin do
    resources :categories
    resources :products do
      resources :product_variants, only: [:new, :create, :edit, :update]
    end
    resources :product_variants, only: [:index, :show, :destroy]
  end
  resources :product_variants, only: [:index, :show] do
    resources :basket_items, only: [:create]
  end
  get '/basket', to: 'baskets#show'
  resources :orders, only: [:create, :show]
  resources :basket_items, only: [:index, :destroy]
  resources :addresses, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category =Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def destroy
    @category =Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/edit.html.erb
<p>Admin</p>
<%= simple_form_for [:admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/index.html.erb
<p>Admin</p>
<% @categories.each do |cat| %>
  <h3><%= link_to cat.name, admin_category_path(cat) %></h3>
<% end %>

<%= link_to "Add a category", new_admin_category_path, class: "btn btn-primary" %>

app/views/admin/categories/new.html.erb
<p>Admin</p>
<%= simple_form_for [:admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/show.html.erb
<p>Admin</p>
<h1><%= @category.name %></h1>
<% @category.products.each do |product| %>
  <p><%= link_to product.name, admin_product_path(product) %></p>
<% end %>
<%= link_to "Edit Category", edit_admin_category_path(@category)  %>
<%= link_to "Delete Category", admin_category_path(@category), method: :delete  %>