config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'product_variants/new'
    get 'product_variants/edit'
  end
  devise_for :users
  root to: 'pages#home'
  namespace :admin do
    resources :categories
    resources :products do
      resources :product_variants, only: [:new, :create, :edit, :update]
    end
    resources :product_variants, only: [:index, :show, :destroy]
  end
  resources :product_variants, only: [:index, :show] do
    resources :basket_items, only: [:create]
  end
  get '/basket', to: 'baskets#show'
  resources :orders, only: [:create, :show]
  resources :basket_items, only: [:index, :destroy]
  resources :addresses, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_variants, dependent: :destroy
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to categories_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to categories_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category_id)
  end
end

app/views/admin/products/edit.html.erb
<p>Admin</p>
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.submit %>
<% end %>

app/views/admin/products/index.html.erb
<p>Admin</p>
<% @products.each do |product| %>
  <h3><%= link_to product.name, admin_product_path(product) %></h3>
<% end %>

<%= link_to "Add a product", new_admin_product_path, class: "btn btn-primary" %>

app/views/admin/products/new.html.erb
<p>Admin</p>
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.submit %>
<% end %>

app/views/admin/products/show.html.erb
<p>Admin</p>
<h1><%= @product.name %></h1>
<h3><%= @product.description %></h3>
<h4>Category: <%= @product.category.name %></h4>

<%= link_to "Edit this product", edit_admin_product_path(@product) %>
<br>
<%= link_to "Delete this product", admin_product_path(@product), method: :delete %>
<br>
<%= link_to "Add a product variant", new_admin_product_product_variant_path(@product), class: "btn btn-primary" %>